/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_vectores (XDR *xdrs, vectores *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vectores_val, (u_int *) &objp->vectores_len, MAX,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion (XDR *xdrs, operacion *objp)
{
	register int32_t *buf;

	 if (!xdr_operacion_arit (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion_t (XDR *xdrs, operacion_t *objp)
{
	register int32_t *buf;

	 if (!xdr_operacion_trig (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion_e (XDR *xdrs, operacion_e *objp)
{
	register int32_t *buf;

	 if (!xdr_ecuacion (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion_v (XDR *xdrs, operacion_v *objp)
{
	register int32_t *buf;

	 if (!xdr_operacion_vect (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion_arit (XDR *xdrs, operacion_arit *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->op))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_funciones_trigonometricas (XDR *xdrs, funciones_trigonometricas *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion_trig (XDR *xdrs, operacion_trig *objp)
{
	register int32_t *buf;

	 if (!xdr_funciones_trigonometricas (xdrs, &objp->func))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->valor))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ecuacion (XDR *xdrs, ecuacion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado (XDR *xdrs, resultado *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->positivo))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->negativo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacion_vect (XDR *xdrs, operacion_vect *objp)
{
	register int32_t *buf;

	 if (!xdr_vectores (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->op))
		 return FALSE;
	 if (!xdr_vectores (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tam))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado_calculadora (XDR *xdrs, resultado_calculadora *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errnum))
		 return FALSE;
	switch (objp->errnum) {
	case 0:
		 if (!xdr_double (xdrs, &objp->resultado_calculadora_u.resultado))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_resultado_calculadora_ecuaciones (XDR *xdrs, resultado_calculadora_ecuaciones *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errnum))
		 return FALSE;
	switch (objp->errnum) {
	case 0:
		 if (!xdr_resultado (xdrs, &objp->resultado_calculadora_ecuaciones_u.res))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_resultado_calculadora_vectores (XDR *xdrs, resultado_calculadora_vectores *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errnum))
		 return FALSE;
	switch (objp->errnum) {
	case 0:
		 if (!xdr_vectores (xdrs, &objp->resultado_calculadora_vectores_u.resultado))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
